name       : python-pythran
version    : 0.11.0
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/p/pythran/pythran-0.11.0.tar.gz : 0b2cba712e09f7630879dff69f268460bfe34a6d6000451b47d598558a92a875
homepage   : https://github.com/serge-sans-paille/pythran
license    : BSD 3-Clause
component  : programming.python
summary    : Ahead of Time compiler for numeric kernels
description: |
    Pythran is an ahead of time compiler for a subset of the Python language, with a focus on scientific computing. It takes a Python module annotated with a few interface descriptions and turns it into a native Python module with the same interface, but (hopefully) faster.
rundeps    :
    - numpy
    - python-beniget
    - python-ply
build      : |
    %python3_setup
install    : |
    %python3_install
