name       : python-pythran
version    : 0.12.0
release    : 3
source     :
    - https://files.pythonhosted.org/packages/source/p/pythran/pythran-0.12.0.tar.gz : eff3dd0d3eebe57372f0d14f82985525e9bcdfb5b1d1010e1932cf9207060f9f
homepage   : https://github.com/serge-sans-paille/pythran
license    : BSD 3-Clause
component  : programming.python
summary    : Ahead of Time compiler for numeric kernels
description: |
    Pythran is an ahead of time compiler for a subset of the Python language, with a focus on scientific computing. It takes a Python module annotated with a few interface descriptions and turns it into a native Python module with the same interface, but (hopefully) faster.
rundeps    :
    - numpy
    - python-beniget
    - python-ply
build      : |
    %python3_setup
install    : |
    %python3_install
